services:
  app:
    build: .
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - nginx
    networks:
      - laravel_network

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

