services:
  app:
    build:
      context: ../../        # Laravel プロジェクトのルートを指定
      dockerfile: Dockerfile # ルートにある Dockerfile を指定
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ../../:/var/www/html
    depends_on:
      - db
    networks:
      - laravel_network

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - ../../:/var/www/html
      - ../../nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel_db
    ports:
      - "3306:3306"
    volumes:
      - dev_dbdata:/var/lib/mysql
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  dev_dbdata:
